// filename  ******************* MyTimer.H **************************
// Ethan Hitchcock, Audrey Wang 4/12/17

// standard ASCII symbols 
#define CR   0x0D
#define LF   0x0A
#define BS   0x08
#define ESC  0x1B
#define SP   0x20       
#define DEL  0x7F
 
//-------------------------Timer_init------------------------
void MyTimerInit(void);

//-------------------------Timer_delay------------------------
void Delay_100ms(void);

